/**
 * @Author: Wendy Guadalupe Magaña Argente <wendylu>
 * @Date:   2017-09-05T22:16:31-05:00
 * @Email:  wendyargente@nube.unadmexico.mx
 * @Project: Turing
 * @Filename: paises.sql
 * @Last modified by:   wendylu
 * @Last modified time: 2017-09-05T22:22:53-05:00
 * @License: MIT
 */



-- CREATE TABLE `pais` (
-- `id` int(11) NOT NULL auto_increment,
-- `country_code` varchar(2) NOT NULL default '',
-- `country_name` varchar(100) NOT NULL default '',
-- PRIMARY KEY (`id`)
-- ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
--
-- Dumping data for table `pais`
--
INSERT INTO `pais` VALUES (null, 'Afghanistan');
INSERT INTO `pais` VALUES (null, 'Albania');
INSERT INTO `pais` VALUES (null, 'Algeria');
INSERT INTO `pais` VALUES (null, 'American Samoa');
INSERT INTO `pais` VALUES (null, 'Andorra');
INSERT INTO `pais` VALUES (null, 'Angola');
INSERT INTO `pais` VALUES (null, 'Anguilla');
INSERT INTO `pais` VALUES (null, 'Antarctica');
INSERT INTO `pais` VALUES (null, 'Antigua and Barbuda');
INSERT INTO `pais` VALUES (null, 'Argentina');
INSERT INTO `pais` VALUES (null, 'Armenia');
INSERT INTO `pais` VALUES (null, 'Aruba');
INSERT INTO `pais` VALUES (null, 'Australia');
INSERT INTO `pais` VALUES (null, 'Austria');
INSERT INTO `pais` VALUES (null, 'Azerbaijan');
INSERT INTO `pais` VALUES (null, 'Bahamas');
INSERT INTO `pais` VALUES (null, 'Bahrain');
INSERT INTO `pais` VALUES (null, 'Bangladesh');
INSERT INTO `pais` VALUES (null, 'Barbados');
INSERT INTO `pais` VALUES (null, 'Belarus');
INSERT INTO `pais` VALUES (null, 'Belgium');
INSERT INTO `pais` VALUES (null, 'Belize');
INSERT INTO `pais` VALUES (null, 'Benin');
INSERT INTO `pais` VALUES (null, 'Bermuda');
INSERT INTO `pais` VALUES (null, 'Bhutan');
INSERT INTO `pais` VALUES (null, 'Bolivia');
INSERT INTO `pais` VALUES (null, 'Bosnia and Herzegovina');
INSERT INTO `pais` VALUES (null, 'Botswana');
INSERT INTO `pais` VALUES (null, 'Bouvet Island');
INSERT INTO `pais` VALUES (null, 'Brazil');
INSERT INTO `pais` VALUES (null, 'British Indian Ocean Territory');
INSERT INTO `pais` VALUES (null, 'Brunei Darussalam');
INSERT INTO `pais` VALUES (null, 'Bulgaria');
INSERT INTO `pais` VALUES (null, 'Burkina Faso');
INSERT INTO `pais` VALUES (null, 'Burundi');
INSERT INTO `pais` VALUES (null, 'Cambodia');
INSERT INTO `pais` VALUES (null, 'Cameroon');
INSERT INTO `pais` VALUES (null, 'Canada');
INSERT INTO `pais` VALUES (null, 'Cape Verde');
INSERT INTO `pais` VALUES (null, 'Cayman Islands');
INSERT INTO `pais` VALUES (null, 'Central African Republic');
INSERT INTO `pais` VALUES (null, 'Chad');
INSERT INTO `pais` VALUES (null, 'Chile');
INSERT INTO `pais` VALUES (null, 'China');
INSERT INTO `pais` VALUES (null, 'Christmas Island');
INSERT INTO `pais` VALUES (null, 'Cocos (Keeling) Islands');
INSERT INTO `pais` VALUES (null, 'Colombia');
INSERT INTO `pais` VALUES (null, 'Comoros');
INSERT INTO `pais` VALUES (null, 'Congo');
INSERT INTO `pais` VALUES (null, 'Cook Islands');
INSERT INTO `pais` VALUES (null, 'Costa Rica');
INSERT INTO `pais` VALUES (null, 'Croatia (Hrvatska)');
INSERT INTO `pais` VALUES (null, 'Cuba');
INSERT INTO `pais` VALUES (null, 'Cyprus');
INSERT INTO `pais` VALUES (null, 'Czech Republic');
INSERT INTO `pais` VALUES (null, 'Denmark');
INSERT INTO `pais` VALUES (null, 'Djibouti');
INSERT INTO `pais` VALUES (null, 'Dominica');
INSERT INTO `pais` VALUES (null, 'Dominican Republic');
INSERT INTO `pais` VALUES (null, 'East Timor');
INSERT INTO `pais` VALUES (null, 'Ecuador');
INSERT INTO `pais` VALUES (null, 'Egypt');
INSERT INTO `pais` VALUES (null, 'El Salvador');
INSERT INTO `pais` VALUES (null, 'Equatorial Guinea');
INSERT INTO `pais` VALUES (null, 'Eritrea');
INSERT INTO `pais` VALUES (null, 'Estonia');
INSERT INTO `pais` VALUES (null, 'Ethiopia');
INSERT INTO `pais` VALUES (null, 'Falkland Islands (Malvinas)');
INSERT INTO `pais` VALUES (null, 'Faroe Islands');
INSERT INTO `pais` VALUES (null, 'Fiji');
INSERT INTO `pais` VALUES (null, 'Finland');
INSERT INTO `pais` VALUES (null, 'France');
INSERT INTO `pais` VALUES (null, 'France, Metropolitan');
INSERT INTO `pais` VALUES (null, 'French Guiana');
INSERT INTO `pais` VALUES (null, 'French Polynesia');
INSERT INTO `pais` VALUES (null, 'French Southern Territories');
INSERT INTO `pais` VALUES (null, 'Gabon');
INSERT INTO `pais` VALUES (null, 'Gambia');
INSERT INTO `pais` VALUES (null, 'Georgia');
INSERT INTO `pais` VALUES (null, 'Germany');
INSERT INTO `pais` VALUES (null, 'Ghana');
INSERT INTO `pais` VALUES (null, 'Gibraltar');
INSERT INTO `pais` VALUES (null, 'Guernsey');
INSERT INTO `pais` VALUES (null, 'Greece');
INSERT INTO `pais` VALUES (null, 'Greenland');
INSERT INTO `pais` VALUES (null, 'Grenada');
INSERT INTO `pais` VALUES (null, 'Guadeloupe');
INSERT INTO `pais` VALUES (null, 'Guam');
INSERT INTO `pais` VALUES (null, 'Guatemala');
INSERT INTO `pais` VALUES (null, 'Guinea');
INSERT INTO `pais` VALUES (null, 'Guinea-Bissau');
INSERT INTO `pais` VALUES (null, 'Guyana');
INSERT INTO `pais` VALUES (null, 'Haiti');
INSERT INTO `pais` VALUES (null, 'Heard and Mc Donald Islands');
INSERT INTO `pais` VALUES (null, 'Honduras');
INSERT INTO `pais` VALUES (null, 'Hong Kong');
INSERT INTO `pais` VALUES (null, 'Hungary');
INSERT INTO `pais` VALUES (null, 'Iceland');
INSERT INTO `pais` VALUES (null, 'India');
INSERT INTO `pais` VALUES (null, 'Isle of Man');
INSERT INTO `pais` VALUES (null, 'Indonesia');
INSERT INTO `pais` VALUES (null, 'Iran (Islamic Republic of)');
INSERT INTO `pais` VALUES (null, 'Iraq');
INSERT INTO `pais` VALUES (null, 'Ireland');
INSERT INTO `pais` VALUES (null, 'Israel');
INSERT INTO `pais` VALUES (null, 'Italy');
INSERT INTO `pais` VALUES (null, 'Ivory Coast');
INSERT INTO `pais` VALUES (null, 'Jersey');
INSERT INTO `pais` VALUES (null, 'Jamaica');
INSERT INTO `pais` VALUES (null, 'Japan');
INSERT INTO `pais` VALUES (null, 'Jordan');
INSERT INTO `pais` VALUES (null, 'Kazakhstan');
INSERT INTO `pais` VALUES (null, 'Kenya');
INSERT INTO `pais` VALUES (null, 'Kiribati');
INSERT INTO `pais` VALUES (null, 'Korea, Democratic People''s Republic of');
INSERT INTO `pais` VALUES (null, 'Korea, Republic of');
INSERT INTO `pais` VALUES (null, 'Kosovo');
INSERT INTO `pais` VALUES (null, 'Kuwait');
INSERT INTO `pais` VALUES (null, 'Kyrgyzstan');
INSERT INTO `pais` VALUES (null, 'Lao People''s Democratic Republic');
INSERT INTO `pais` VALUES (null, 'Latvia');
INSERT INTO `pais` VALUES (null, 'Lebanon');
INSERT INTO `pais` VALUES (null, 'Lesotho');
INSERT INTO `pais` VALUES (null, 'Liberia');
INSERT INTO `pais` VALUES (null, 'Libyan Arab Jamahiriya');
INSERT INTO `pais` VALUES (null, 'Liechtenstein');
INSERT INTO `pais` VALUES (null, 'Lithuania');
INSERT INTO `pais` VALUES (null, 'Luxembourg');
INSERT INTO `pais` VALUES (null, 'Macau');
INSERT INTO `pais` VALUES (null, 'Macedonia');
INSERT INTO `pais` VALUES (null, 'Madagascar');
INSERT INTO `pais` VALUES (null, 'Malawi');
INSERT INTO `pais` VALUES (null, 'Malaysia');
INSERT INTO `pais` VALUES (null, 'Maldives');
INSERT INTO `pais` VALUES (null, 'Mali');
INSERT INTO `pais` VALUES (null, 'Malta');
INSERT INTO `pais` VALUES (null, 'Marshall Islands');
INSERT INTO `pais` VALUES (null, 'Martinique');
INSERT INTO `pais` VALUES (null, 'Mauritania');
INSERT INTO `pais` VALUES (null, 'Mauritius');
INSERT INTO `pais` VALUES (null, 'Mayotte');
INSERT INTO `pais` VALUES (null, 'Mexico');
INSERT INTO `pais` VALUES (null, 'Micronesia, Federated States of');
INSERT INTO `pais` VALUES (null, 'Moldova, Republic of');
INSERT INTO `pais` VALUES (null, 'Monaco');
INSERT INTO `pais` VALUES (null, 'Mongolia');
INSERT INTO `pais` VALUES (null, 'Montenegro');
INSERT INTO `pais` VALUES (null, 'Montserrat');
INSERT INTO `pais` VALUES (null, 'Morocco');
INSERT INTO `pais` VALUES (null, 'Mozambique');
INSERT INTO `pais` VALUES (null, 'Myanmar');
INSERT INTO `pais` VALUES (null, 'Namibia');
INSERT INTO `pais` VALUES (null, 'Nauru');
INSERT INTO `pais` VALUES (null, 'Nepal');
INSERT INTO `pais` VALUES (null, 'Netherlands');
INSERT INTO `pais` VALUES (null, 'Netherlands Antilles');
INSERT INTO `pais` VALUES (null, 'New Caledonia');
INSERT INTO `pais` VALUES (null, 'New Zealand');
INSERT INTO `pais` VALUES (null, 'Nicaragua');
INSERT INTO `pais` VALUES (null, 'Niger');
INSERT INTO `pais` VALUES (null, 'Nigeria');
INSERT INTO `pais` VALUES (null, 'Niue');
INSERT INTO `pais` VALUES (null, 'Norfolk Island');
INSERT INTO `pais` VALUES (null, 'Northern Mariana Islands');
INSERT INTO `pais` VALUES (null, 'Norway');
INSERT INTO `pais` VALUES (null, 'Oman');
INSERT INTO `pais` VALUES (null, 'Pakistan');
INSERT INTO `pais` VALUES (null, 'Palau');
INSERT INTO `pais` VALUES (null, 'Palestine');
INSERT INTO `pais` VALUES (null, 'Panama');
INSERT INTO `pais` VALUES (null, 'Papua New Guinea');
INSERT INTO `pais` VALUES (null, 'Paraguay');
INSERT INTO `pais` VALUES (null, 'Peru');
INSERT INTO `pais` VALUES (null, 'Philippines');
INSERT INTO `pais` VALUES (null, 'Pitcairn');
INSERT INTO `pais` VALUES (null, 'Poland');
INSERT INTO `pais` VALUES (null, 'Portugal');
INSERT INTO `pais` VALUES (null, 'Puerto Rico');
INSERT INTO `pais` VALUES (null, 'Qatar');
INSERT INTO `pais` VALUES (null, 'Reunion');
INSERT INTO `pais` VALUES (null, 'Romania');
INSERT INTO `pais` VALUES (null, 'Russian Federation');
INSERT INTO `pais` VALUES (null, 'Rwanda');
INSERT INTO `pais` VALUES (null, 'Saint Kitts and Nevis');
INSERT INTO `pais` VALUES (null, 'Saint Lucia');
INSERT INTO `pais` VALUES (null, 'Saint Vincent and the Grenadines');
INSERT INTO `pais` VALUES (null, 'Samoa');
INSERT INTO `pais` VALUES (null, 'San Marino');
INSERT INTO `pais` VALUES (null, 'Sao Tome and Principe');
INSERT INTO `pais` VALUES (null, 'Saudi Arabia');
INSERT INTO `pais` VALUES (null, 'Senegal');
INSERT INTO `pais` VALUES (null, 'Serbia');
INSERT INTO `pais` VALUES (null, 'Seychelles');
INSERT INTO `pais` VALUES (null, 'Sierra Leone');
INSERT INTO `pais` VALUES (null, 'Singapore');
INSERT INTO `pais` VALUES (null, 'Slovakia');
INSERT INTO `pais` VALUES (null, 'Slovenia');
INSERT INTO `pais` VALUES (null, 'Solomon Islands');
INSERT INTO `pais` VALUES (null, 'Somalia');
INSERT INTO `pais` VALUES (null, 'South Africa');
INSERT INTO `pais` VALUES (null, 'South Georgia South Sandwich Islands');
INSERT INTO `pais` VALUES (null, 'Spain');
INSERT INTO `pais` VALUES (null, 'Sri Lanka');
INSERT INTO `pais` VALUES (null, 'St. Helena');
INSERT INTO `pais` VALUES (null, 'St. Pierre and Miquelon');
INSERT INTO `pais` VALUES (null, 'Sudan');
INSERT INTO `pais` VALUES (null, 'Suriname');
INSERT INTO `pais` VALUES (null, 'Svalbard and Jan Mayen Islands');
INSERT INTO `pais` VALUES (null, 'Swaziland');
INSERT INTO `pais` VALUES (null, 'Sweden');
INSERT INTO `pais` VALUES (null, 'Switzerland');
INSERT INTO `pais` VALUES (null, 'Syrian Arab Republic');
INSERT INTO `pais` VALUES (null, 'Taiwan');
INSERT INTO `pais` VALUES (null, 'Tajikistan');
INSERT INTO `pais` VALUES (null, 'Tanzania, United Republic of');
INSERT INTO `pais` VALUES (null, 'Thailand');
INSERT INTO `pais` VALUES (null, 'Togo');
INSERT INTO `pais` VALUES (null, 'Tokelau');
INSERT INTO `pais` VALUES (null, 'Tonga');
INSERT INTO `pais` VALUES (null, 'Trinidad and Tobago');
INSERT INTO `pais` VALUES (null, 'Tunisia');
INSERT INTO `pais` VALUES (null, 'Turkey');
INSERT INTO `pais` VALUES (null, 'Turkmenistan');
INSERT INTO `pais` VALUES (null, 'Turks and Caicos Islands');
INSERT INTO `pais` VALUES (null, 'Tuvalu');
INSERT INTO `pais` VALUES (null, 'Uganda');
INSERT INTO `pais` VALUES (null, 'Ukraine');
INSERT INTO `pais` VALUES (null, 'United Arab Emirates');
INSERT INTO `pais` VALUES (null, 'United Kingdom');
INSERT INTO `pais` VALUES (null, 'United States');
INSERT INTO `pais` VALUES (null, 'United States minor outlying islands');
INSERT INTO `pais` VALUES (null, 'Uruguay');
INSERT INTO `pais` VALUES (null, 'Uzbekistan');
INSERT INTO `pais` VALUES (null, 'Vanuatu');
INSERT INTO `pais` VALUES (null, 'Vatican City State');
INSERT INTO `pais` VALUES (null, 'Venezuela');
INSERT INTO `pais` VALUES (null, 'Vietnam');
INSERT INTO `pais` VALUES (null, 'Virgin Islands (British)');
INSERT INTO `pais` VALUES (null, 'Virgin Islands (U.S.)');
INSERT INTO `pais` VALUES (null, 'Wallis and Futuna Islands');
INSERT INTO `pais` VALUES (null, 'Western Sahara');
INSERT INTO `pais` VALUES (null, 'Yemen');
INSERT INTO `pais` VALUES (null, 'Zaire');
INSERT INTO `pais` VALUES (null, 'Zambia');
INSERT INTO `pais` VALUES (null, 'Zimbabwe');
