# @Author: Wendy Guadalupe Magaña Argente <wendylu>
# @Date:   2017-09-05T05:17:09-05:00
# @Email:  wendyargente@nube.unadmexico.mx
# @Project: Turing
# @Filename: _config_dev.yml
# @Last modified by:   wendylu
# @Last modified time: 2017-09-05T09:15:18-05:00
# @License: MIT



# Crea sitios estáticos de forma local
baseurl: ""
url: ""

exclude: [documentacion, Gemfile, Gemfile.lock]

keep_files: [basedatos.php, configuracion.php, form-insertar.php, insertar.php, consulta.php, borrado.php]
